FROM alpine:3.24

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata

COPY $TARGETPLATFORM/khunquant /usr/local/bin/khunquant
COPY $TARGETPLATFORM/khunquant-launcher /usr/local/bin/khunquant-launcher
COPY $TARGETPLATFORM/khunquant-launcher-tui /usr/local/bin/khunquant-launcher-tui

ENTRYPOINT ["khunquant-launcher"]
CMD ["-console", "-public", "-no-browser"]