/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as CredentialsRouteImport } from './routes/credentials'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as PortfoliosRouteRouteImport } from './routes/portfolios/route'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as AgentConfigRouteImport } from './routes/agent/config'
import { Route as AgentCronRouteImport } from './routes/agent/cron'
import { Route as AgentMemoryRouteImport } from './routes/agent/memory'
import { Route as AgentPairingRouteImport } from './routes/agent/pairing'
import { Route as AgentSkillsRouteImport } from './routes/agent/skills'
import { Route as AgentToolsRouteImport } from './routes/agent/tools'
import { Route as ChannelsNameRouteImport } from './routes/channels/$name'
import { Route as ConfigRawRouteImport } from './routes/config.raw'
import { Route as PortfoliosNameRouteImport } from './routes/portfolios/$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const CredentialsRoute = CredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosRouteRoute = PortfoliosRouteRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentConfigRoute = AgentConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AgentRoute,
} as any)
const AgentCronRoute = AgentCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AgentRoute,
} as any)
const AgentMemoryRoute = AgentMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AgentRoute,
} as any)
const AgentPairingRoute = AgentPairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => AgentRoute,
} as any)
const AgentSkillsRoute = AgentSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AgentRoute,
} as any)
const AgentToolsRoute = AgentToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AgentRoute,
} as any)
const ChannelsNameRoute = ChannelsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => ChannelsRouteRoute,
} as any)
const ConfigRawRoute = ConfigRawRouteImport.update({
  id: '/raw',
  path: '/raw',
  getParentRoute: () => ConfigRoute,
} as any)
const PortfoliosNameRoute = PortfoliosNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => PortfoliosRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/portfolios': typeof PortfoliosRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/sandbox': typeof SandboxRoute
  '/agent/config': typeof AgentConfigRoute
  '/agent/cron': typeof AgentCronRoute
  '/agent/memory': typeof AgentMemoryRoute
  '/agent/pairing': typeof AgentPairingRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/portfolios/$name': typeof PortfoliosNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/portfolios': typeof PortfoliosRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/sandbox': typeof SandboxRoute
  '/agent/config': typeof AgentConfigRoute
  '/agent/cron': typeof AgentCronRoute
  '/agent/memory': typeof AgentMemoryRoute
  '/agent/pairing': typeof AgentPairingRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/portfolios/$name': typeof PortfoliosNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRouteRouteWithChildren
  '/portfolios': typeof PortfoliosRouteRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/config': typeof ConfigRouteWithChildren
  '/credentials': typeof CredentialsRoute
  '/logs': typeof LogsRoute
  '/models': typeof ModelsRoute
  '/sandbox': typeof SandboxRoute
  '/agent/config': typeof AgentConfigRoute
  '/agent/cron': typeof AgentCronRoute
  '/agent/memory': typeof AgentMemoryRoute
  '/agent/pairing': typeof AgentPairingRoute
  '/agent/skills': typeof AgentSkillsRoute
  '/agent/tools': typeof AgentToolsRoute
  '/channels/$name': typeof ChannelsNameRoute
  '/config/raw': typeof ConfigRawRoute
  '/portfolios/$name': typeof PortfoliosNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/portfolios'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/models'
    | '/sandbox'
    | '/agent/config'
    | '/agent/cron'
    | '/agent/memory'
    | '/agent/pairing'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/portfolios/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/portfolios'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/models'
    | '/sandbox'
    | '/agent/config'
    | '/agent/cron'
    | '/agent/memory'
    | '/agent/pairing'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/portfolios/$name'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/portfolios'
    | '/agent'
    | '/config'
    | '/credentials'
    | '/logs'
    | '/models'
    | '/sandbox'
    | '/agent/config'
    | '/agent/cron'
    | '/agent/memory'
    | '/agent/pairing'
    | '/agent/skills'
    | '/agent/tools'
    | '/channels/$name'
    | '/config/raw'
    | '/portfolios/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRouteRoute: typeof ChannelsRouteRouteWithChildren
  PortfoliosRouteRoute: typeof PortfoliosRouteRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  ConfigRoute: typeof ConfigRouteWithChildren
  CredentialsRoute: typeof CredentialsRoute
  LogsRoute: typeof LogsRoute
  ModelsRoute: typeof ModelsRoute
  SandboxRoute: typeof SandboxRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credentials': {
      id: '/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof CredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios': {
      id: '/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof PortfoliosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/config': {
      id: '/agent/config'
      path: '/config'
      fullPath: '/agent/config'
      preLoaderRoute: typeof AgentConfigRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/cron': {
      id: '/agent/cron'
      path: '/cron'
      fullPath: '/agent/cron'
      preLoaderRoute: typeof AgentCronRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/memory': {
      id: '/agent/memory'
      path: '/memory'
      fullPath: '/agent/memory'
      preLoaderRoute: typeof AgentMemoryRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/pairing': {
      id: '/agent/pairing'
      path: '/pairing'
      fullPath: '/agent/pairing'
      preLoaderRoute: typeof AgentPairingRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/skills': {
      id: '/agent/skills'
      path: '/skills'
      fullPath: '/agent/skills'
      preLoaderRoute: typeof AgentSkillsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/tools': {
      id: '/agent/tools'
      path: '/tools'
      fullPath: '/agent/tools'
      preLoaderRoute: typeof AgentToolsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/channels/$name': {
      id: '/channels/$name'
      path: '/$name'
      fullPath: '/channels/$name'
      preLoaderRoute: typeof ChannelsNameRouteImport
      parentRoute: typeof ChannelsRouteRoute
    }
    '/config/raw': {
      id: '/config/raw'
      path: '/raw'
      fullPath: '/config/raw'
      preLoaderRoute: typeof ConfigRawRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/portfolios/$name': {
      id: '/portfolios/$name'
      path: '/$name'
      fullPath: '/portfolios/$name'
      preLoaderRoute: typeof PortfoliosNameRouteImport
      parentRoute: typeof PortfoliosRouteRoute
    }
  }
}

interface ChannelsRouteRouteChildren {
  ChannelsNameRoute: typeof ChannelsNameRoute
}

const ChannelsRouteRouteChildren: ChannelsRouteRouteChildren = {
  ChannelsNameRoute: ChannelsNameRoute,
}

const ChannelsRouteRouteWithChildren = ChannelsRouteRoute._addFileChildren(
  ChannelsRouteRouteChildren,
)

interface PortfoliosRouteRouteChildren {
  PortfoliosNameRoute: typeof PortfoliosNameRoute
}

const PortfoliosRouteRouteChildren: PortfoliosRouteRouteChildren = {
  PortfoliosNameRoute: PortfoliosNameRoute,
}

const PortfoliosRouteRouteWithChildren = PortfoliosRouteRoute._addFileChildren(
  PortfoliosRouteRouteChildren,
)

interface AgentRouteChildren {
  AgentConfigRoute: typeof AgentConfigRoute
  AgentCronRoute: typeof AgentCronRoute
  AgentMemoryRoute: typeof AgentMemoryRoute
  AgentPairingRoute: typeof AgentPairingRoute
  AgentSkillsRoute: typeof AgentSkillsRoute
  AgentToolsRoute: typeof AgentToolsRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentConfigRoute: AgentConfigRoute,
  AgentCronRoute: AgentCronRoute,
  AgentMemoryRoute: AgentMemoryRoute,
  AgentPairingRoute: AgentPairingRoute,
  AgentSkillsRoute: AgentSkillsRoute,
  AgentToolsRoute: AgentToolsRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface ConfigRouteChildren {
  ConfigRawRoute: typeof ConfigRawRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigRawRoute: ConfigRawRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRouteRoute: ChannelsRouteRouteWithChildren,
  PortfoliosRouteRoute: PortfoliosRouteRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  ConfigRoute: ConfigRouteWithChildren,
  CredentialsRoute: CredentialsRoute,
  LogsRoute: LogsRoute,
  ModelsRoute: ModelsRoute,
  SandboxRoute: SandboxRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
